var nameList = [
   "Time",
   "Past",
   "Future",
   "Dev",
   "Fly",
   "Flying",
   "Soar",
   "Soaring",
   "Power",
   "Falling",
   "Fall",
   "Jump",
   "Cliff",
   "Mountain",
   "Rend",
   "Red",
   "Blue",
   "Green",
   "Yellow",
   "Gold",
   "Demon",
   "Demonic",
   "Panda",
   "Cat",
   "Kitty",
   "Kitten",
   "Zero",
   "Memory",
   "Trooper",
   "XX",
   "Bandit",
   "Fear",
   "Light",
   "Glow",
   "Tread",
   "Deep",
   "Deeper",
   "Deepest",
   "Mine",
   "Your",
   "Worst",
   "Enemy",
   "Hostile",
   "Force",
   "Video",
   "Game",
   "Donkey",
   "Mule",
   "Colt",
   "Cult",
   "Cultist",
   "Magnum",
   "Gun",
   "Assault",
   "Recon",
   "Trap",
   "Trapper",
   "Redeem",
   "Code",
   "Script",
   "Writer",
   "Near",
   "Close",
   "Open",
   "Cube",
   "Circle",
   "Geo",
   "Genome",
   "Germ",
   "Spaz",
   "Shot",
   "Echo",
   "Beta",
   "Alpha",
   "Gamma",
   "Omega",
   "Seal",
   "Squid",
   "Money",
   "Cash",
   "Lord",
   "King",
   "Duke",
   "Rest",
   "Fire",
   "Flame",
   "Morrow",
   "Break",
   "Breaker",
   "Numb",
   "Ice",
   "Cold",
   "Rotten",
   "Sick",
   "Sickly",
   "Janitor",
   "Camel",
   "Rooster",
   "Sand",
   "Desert",
   "Dessert",
   "Hurdle",
   "Racer",
   "Eraser",
   "Erase",
   "Big",
   "Small",
   "Short",
   "Tall",
   "Sith",
   "Bounty",
   "Hunter",
   "Cracked",
   "Broken",
   "Sad",
   "Happy",
   "Joy",
   "Joyful",
   "Crimson",
   "Destiny",
   "Deceit",
   "Lies",
   "Lie",
   "Honest",
   "Destined",
   "Bloxxer",
   "Hawk",
   "Eagle",
   "Hawker",
   "Walker",
   "Zombie",
   "Sarge",
   "Capt",
   "Captain",
   "Punch",
   "One",
   "Two",
   "Uno",
   "Slice",
   "Slash",
   "Melt",
   "Melted",
   "Melting",
   "Fell",
   "Wolf",
   "Hound",
   "Legacy",
   "Sharp",
   "Dead",
   "Mew",
   "Chuckle",
   "Bubba",
   "Bubble",
   "Sandwich",
   "Smasher",
   "Extreme",
   "Multi",
   "Universe",
   "Ultimate",
   "Death",
   "Ready",
   "Monkey",
   "Elevator",
   "Wrench",
   "Grease",
   "Head",
   "Theme",
   "Grand",
   "Cool",
   "Kid",
   "Boy",
   "Girl",
   "Vortex",
   "Paradox",
];
export function generateName() {
   return nameList[Math.floor(Math.random() * nameList.length)];
}

const msgs = [
   "Love all, trust a few, do wrong to none",
   "😎😎😎",
   "You call it madness, but I call it love",
   "Ohio is a great place",
   "We can only learn to love by loving",
   "Life is the flower for which love is the honey, A life lived in love will never be dull",
   "Adam calling Jamie a silent walrus",
   "🤣😂🤣 lol...",
   "Grant the best mythBuster",
   "Lmao",
   "Jamie is cool in his own mysteries ways 😎",
   "First 🥇!!!",
   "UDP is better in the COVID era since it avoids unnecessary handshakes",
   "Guys check out my new channel ... Follow for Follow ⭐🤩",
   "Who is watching it in 2099 💞",
   "Like 👍🏿 Share and Subscribe",
   "Hehehe sounds cool",
   "Thats so funny",
   "🚀🚀🚀🚀🚀",
   "😻😻😻",
   "Someone give this guy a Medal 🏅🏅🏅",
   "Algorithm is word used by programmers when they don't want to explain how their code works 🤣",
   "All the best guys",
   "🔥🔥🔥🔥🔥",
];
export function generateString() {
   return msgs[Math.floor(Math.random() * msgs.length)];
}
